### ISSUE TITLE
Setup the structure of the project

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/search#3]
This comes as the result of the oacore/dashboard. I would like to structure it as:

- design
  - foundation (separate package)
  - elements (separate package)
  - modules
  - templates
- pages
  - data-providers
  - outputs ⏰
  - works ⏰
  - search ⏰

_Originally posted by @viktor-yakubiv in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjgwNjk2ODUzOnYy/pull_request_review_threads/discussion_

**Comment by Joozty** [comment]
I think we can close it now. We have a decent structure we can work with.
