### ISSUE TITLE
Split custom Next <App> to framework-dependent and -independent parts

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/search#4]
In general, I imagine `pages` + `next.config.js` as a thin framework layer and the rest of the repository if the completely independent 'project'.

The app hooks should be in a separate place, e.g. `app` or `main` in the project root.  

`_app.jsx` should be a simple link/wrapper of the main component from the other place.

Comes from [search#1 (comment)](https://github.com/oacore/search/pull/1#discussion_r450305076)

**Comment by Joozty** [comment]
What if these hooks are dependent on next framework? In that case it makes sense having it under pages folder, doesn't it? It makes sense for all future hooks to have them in separate place but those app hooks are probably fine where they are.  

The main component makes sense and will appear in future when we have a better image if this project.

**Comment by viktor-yakubiv** [comment]
I see your point, it's tricky. Let's do this step-by-step and then we will see.

We can have another framework-dependent module and probably should have one. For this particular issue, I do not like that Next.js picks up every single file when you run `next build` so you get pages like `_app/hooks` what does not look correct in the logs.

Also, I would like to keep `pages` as thin as possible because it's more routes and SRR setup than actual page template. However, I am not strong in this because I have not developed an opinion about it. Do you have any ideas about how we should structure it properly?

**Comment by Joozty** [comment]
I didn't realize that it created new page entries. It makes absolutely sense to move it somewhere else. I am more tempted to `app` folder then. 

Thanks for explanation.

**Comment by viktor-yakubiv** [comment]
I did not notice that at the beginning too. This is how Next works and I think this should be rather avoided in projects than fixed on the framework level 🙂
