### ISSUE TITLE
Data-providers layout is broken

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/search#45]
I checked it works from time to time. The problem may be hidden somewhere in the CSS loading sequence.

<img width="1401" alt="Screenshot 2020-08-03 at 16 46 16" src="https://user-images.githubusercontent.com/8440244/89189899-575b1e00-d5a9-11ea-9b6c-ec0c97075460.png">

**Comment by Joozty** [comment]
Yeah it's most likely the nextjs bug we faced previously. Also the percentage positioning doesn't work very well on wider monitors as you already mentioned because percentage is calculated from width not from height it should be solved within this task too.
